hyperparams:
  block_size: 128
  batch_size: 64
  vocab_size: 16000
  n_layer: 6
  n_head: 8
  d_model: 512
  dropout: 0.1
  lr: 0.006
  weight_decay: 0.0
  evals_per_epoch: 3
  epochs: 7
  seed: 1337
  num_titles: 100000
  val_frac: 0.10
  log_file: "./logs/mainrun.log"
